[versions]
mod-version = "0.1.0"

# Minecraft / Fabric
minecraft = "1.21.11"
yarn-mappings = "1.21.11+build.3"
fabric-loader = "0.18.2"

# Fabric Loom
loom = "1.14.10"

# Meteor Client
meteor = "1.21.11-SNAPSHOT"

[libraries]
# Minecraft
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

# Yarn mappings
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }

# Fabric Loader
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

# Meteor Client
meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }


